# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=1000)),
                ('theme', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_streaming', models.BooleanField(default=False)),
                ('is_suggested_by_user', models.BooleanField(default=False)),
                ('is_suggested_for_user', models.BooleanField(default=False)),
            ],
        ),
    ]
