# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_suggested_for_user',
        ),
        migrations.AddField(
            model_name='song',
            name='pushed_to',
            field=models.CharField(choices=[(1, 'bruk')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='theme',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
