# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-20 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_auto_20180619_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='pushed_to',
            field=models.IntegerField(choices=[(1, 'bruk'), (2, 'abebe'), (3, 'chala'), (4, ''), (5, 'hello'), (6, 'belete'), (7, 'belay'), (8, 'mami'), (9, 'mamii'), (10, 'brukk')], default=0),
        ),
    ]
