# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-28 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180620_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pushed_to',
            field=models.IntegerField(choices=[(1, 'bruk'), (17, 'a')], default=0),
        ),
    ]
